version = 0.1

[default.deploy.parameters]
stack_name = "askmybank-api"
resolve_s3 = true
s3_prefix = "askmybank-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "VectorsBucket=\"askmybank-vectors\" BedrockRegion=\"us-east-1\" ClickHouseHost=\"u52z4ehjt5.ap-southeast-2.aws.clickhouse.cloud\" ClickHouseUser=\"default\" ClickHousePassword=\"g0qcwNqFw~Psg\" Stage=\"prod\" DemoApiKey=\"askmybank-demo-2025\" OrkesApiUrl=\"https://developer.orkescloud.com/api\" OrkesKeyId=\"eupcdab254d2-4ec2-11f1-be67-1eee6a213867\" OrkesKeySecret=\"w7IM8ETVXO34vsvsHEZPE2aaJKZ9a8QtvLmOJm7gsErid2r3\" LangfuseSecretKey=\"sk-lf-31a968a6-bd0b-4151-8527-6498cb2aa542\" LangfusePublicKey=\"pk-lf-f43a502f-f5fe-4ab8-bac4-aa651f4c6c47\" LangfuseHost=\"https://jp.cloud.langfuse.com\" TemporalAddress=\"askmybank-pilot.kjpto.tmprl.cloud:7233\" TemporalNamespace=\"askmybank-pilot.kjpto\" TemporalApiKey=\"REPLACE_WITH_TEMPORAL_API_KEY\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
